Repository uphold/http-request-signature, pull requests merged in 2019-10, with the labels that each got.

#11 Add license to README
  README.md
Labels: hacktoberfest

#12 Add badges to README
  README.md
Labels: hacktoberfest

#13 Add install steps to README
  README.md
Labels: hacktoberfest

#14 Update dev dependencies
  package.json
  yarn.lock
Labels: support

#15 Update @uphold/github-changelog-generator to v1.0.1
  package.json
  yarn.lock
Labels: enhancement, hacktoberfest
